import { useEffect, useMemo, useState } from 'react'
import { AnimatePresence, motion, useMotionValueEvent, useReducedMotion, useScroll, useSpring } from 'framer-motion'
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3, CheckCircle2, Database, Gauge, Menu, Plane, RefreshCw, Repeat2, Route, Search, ShieldCheck, Sparkles, TrendingUp, X } from 'lucide-react'

type RouteData = { id:string; from:string; to:string; fare:number; change:number; apix:number; apixChange:number; volatility:string; confidence:number; range:string; points:number[]; expected:number[] }
const routes:RouteData[]=[
 {id:'DEL-BOM',from:'DEL',to:'BOM',fare:5842,change:6.8,apix:112.6,apixChange:3.1,volatility:'Moderate',confidence:92,range:'₹5.2K – ₹6.1K',points:[5200,5360,5290,5480,5540,5720,5842],expected:[5100,5200,5280,5360,5450,5540,5620]},
 {id:'DEL-BLR',from:'DEL',to:'BLR',fare:6930,change:-2.1,apix:104.2,apixChange:-1.3,volatility:'Low',confidence:89,range:'₹6.4K – ₹7.2K',points:[7240,7180,7070,7120,6990,7040,6930],expected:[6900,6910,6920,6930,6940,6950,6960]},
 {id:'BOM-BLR',from:'BOM',to:'BLR',fare:4910,change:1.7,apix:107.8,apixChange:.8,volatility:'Low',confidence:95,range:'₹4.6K – ₹5.2K',points:[4680,4730,4710,4790,4850,4820,4910],expected:[4700,4740,4770,4800,4830,4860,4890]},
 {id:'BLR-HYD',from:'BLR',to:'HYD',fare:3840,change:4.2,apix:109.1,apixChange:2.2,volatility:'Moderate',confidence:91,range:'₹3.5K – ₹4.1K',points:[3510,3480,3620,3590,3700,3750,3840],expected:[3500,3540,3580,3620,3660,3700,3740]},
 {id:'MAA-DEL',from:'MAA',to:'DEL',fare:7120,change:3.9,apix:111.3,apixChange:2.6,volatility:'High',confidence:86,range:'₹6.5K – ₹7.4K',points:[6540,6610,6730,6680,6890,7010,7120],expected:[6500,6590,6670,6760,6840,6930,7010]},
 {id:'DEL-CCU',from:'DEL',to:'CCU',fare:6215,change:3.4,apix:110.4,apixChange:1.9,volatility:'Moderate',confidence:90,range:'₹5.8K – ₹6.6K',points:[5790,5880,5840,5960,6030,6140,6215],expected:[5800,5870,5940,6010,6080,6150,6220]}
]
const airportNames:Record<string,string>={DEL:'Delhi',BOM:'Mumbai',BLR:'Bengaluru',HYD:'Hyderabad',MAA:'Chennai',CCU:'Kolkata'}, airports=Object.keys(airportNames), windows=['T+1','T+7','T+15','T+30','T+45']
const windowCopy:Record<string,string>={'T+1':'Booking tomorrow','T+7':'Booking 7 days ahead','T+15':'Booking 15 days ahead','T+30':'Booking one month ahead','T+45':'Booking 45 days ahead'}
const money=(n:number)=>`₹${Math.round(n).toLocaleString('en-IN')}`
const reveal={initial:{opacity:0,y:20},whileInView:{opacity:1,y:0},viewport:{once:true,amount:.18},transition:{duration:.65,ease:[.22,1,.36,1]}}

function Reveal({children,className='',delay=0}:{children:React.ReactNode;className?:string;delay?:number}){return <motion.div className={className} {...reveal} transition={{...reveal.transition,delay}}>{children}</motion.div>}
function Count({value,fare=false,suffix=''}:{value:number;fare?:boolean;suffix?:string}){const reduced=useReducedMotion(),[n,setN]=useState(reduced?value:0);useEffect(()=>{if(reduced){setN(value);return}const from=n,start=performance.now();let frame=0;const tick=(now:number)=>{const p=Math.min(1,(now-start)/650);setN(from+(value-from)*(1-Math.pow(1-p,3)));if(p<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[value]);return <>{fare?money(n):Math.round(n).toLocaleString('en-IN')}{suffix}</>}
function Change({value,light=false}:{value:number;light?:boolean}){const up=value>=0;return <span className={`change ${up?'up':'down'} ${light?'light':''}`}>{up?<ArrowUpRight/>:<ArrowDownRight/>}{Math.abs(value)}%</span>}
function Spark({points,dark=false}:{points:number[];dark?:boolean}){const min=Math.min(...points),max=Math.max(...points),p=points.map((v,i)=>`${i*120/(points.length-1)},${38-(v-min)/Math.max(1,max-min)*28}`).join(' '),last=p.split(' ');return <svg className="spark" viewBox="0 0 120 44"><polyline points={p} fill="none" stroke={dark?'#77A7F7':'#3578E5'} strokeWidth="2" strokeLinecap="round"/><circle cx="120" cy={last[last.length-1].split(',')[1]} r="3" fill="#F3A94D"/></svg>}
function Intro({eyebrow,title,children,light=false}:{eyebrow:string;title:string;children:string;light?:boolean}){return <Reveal className={`intro ${light?'light':''}`}><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p>{children}</p></Reveal>}
function Progress(){const{scrollYProgress}=useScroll(),x=useSpring(scrollYProgress,{stiffness:120,damping:30});return <motion.div className="scroll-progress" style={{scaleX:x}}/>}

function LiveCard(){const[a,setA]=useState(0),d=routes[a];useEffect(()=>{const id=setInterval(()=>setA(v=>(v+1)%routes.length),4400);return()=>clearInterval(id)},[]);return <aside className="hero-card"><div className="card-grid"/><div className="hero-card-head"><div><p className="technical">LIVE INTELLIGENCE</p><div><strong>108.4</strong><Change value={3.2}/></div><span>India APIx</span></div><span className="live-pill"><i/>Live</span></div><AnimatePresence mode="wait"><motion.div key={d.id} className="hero-route" initial={{opacity:0,y:6}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-5}}><div><span>{d.from} → {d.to}</span><strong><Count value={d.fare} fare/></strong></div><Change value={d.change}/><Spark points={d.points}/></motion.div></AnimatePresence><div className="hero-card-foot"><span>WINDOW / T+07</span><span>SYNC / 02M</span></div></aside>}
function Ticker(){const items=['AIRFARE MARKET PULSE','APIx 108.4 ↑3.2%','DEL → BOM ₹5,842 ↑6.8%','DEL → BLR ₹6,930 ↓2.1%','BOM → BLR ₹4,910 ↑1.7%'];return <div className="ticker"><div>{[...items,...items].map((x,i)=><span key={i}><i/>{x}</span>)}</div></div>}
function Hero(){const[open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false),[active,setActive]=useState('explorer'),{scrollY}=useScroll(),nav=[['Index','explorer'],['Methodology','methodology'],['Signals','signals'],['Coverage','coverage']];useMotionValueEvent(scrollY,'change',y=>setScrolled(y>60));useEffect(()=>{const o=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&setActive(e.target.id)),{rootMargin:'-35% 0px -55%'});nav.forEach(([,id])=>{const e=document.getElementById(id);if(e)o.observe(e)});return()=>o.disconnect()},[]);return <section id="start" className="hero"><video src="https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260328_091828_e240eb17-6edc-4129-ad9d-98678e3fd238.mp4" autoPlay muted loop playsInline/><div className="hero-overlay"/><header className={scrolled?'navbar scrolled':'navbar'}><nav><a href="#start" className="brand"><Plane/>AeroIndex</a><div className="nav-links">{nav.map(([l,id])=><a className={active===id?'active':''} href={`#${id}`} key={id}>{l}</a>)}</div><a href="#explorer" className="nav-cta">Explore Index</a><button onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></nav>{open&&<div className="mobile-menu">{nav.map(([l,id])=><a href={`#${id}`} key={id} onClick={()=>setOpen(false)}>{l}</a>)}</div>}</header><div className="hero-content"><div className="hero-copy"><p className="eyebrow">India's real-time airfare intelligence</p><h1><span>See fares.</span><strong>Understand the market.</strong></h1><p>A real-time airfare price index tracking how flight prices move across India — across routes, airlines, and advance booking windows.</p><div><a href="#explorer" className="button primary">Explore Live Index <ArrowRight/></a><a href="#methodology" className="button secondary">How It Works</a></div></div><LiveCard/></div><Ticker/></section>}

function Segments({items,active,set,id}:{items:string[];active:string;set:(x:string)=>void;id:string}){return <div className="segments">{items.map(x=><button key={x} onClick={()=>set(x)}>{active===x&&<motion.i layoutId={id}/>}<span>{x}</span></button>)}</div>}
function FareChart({d}:{d:RouteData}){const w=660,h=220,pad=34,all=[...d.points,...d.expected],min=Math.min(...all)*.97,max=Math.max(...all)*1.03,pt=(v:number,i:number)=>[pad+i*(w-pad*2)/(d.points.length-1),h-pad-(v-min)/(max-min)*(h-pad*2)],path=d.points.map((v,i)=>`${i?'L':'M'} ${pt(v,i).join(' ')}`).join(' '),exp=d.expected.map((v,i)=>`${i?'L':'M'} ${pt(v,i).join(' ')}`).join(' '),last=pt(d.points[d.points.length-1],6);return <div className="chart"><div><span>{d.from} → {d.to} / 7 observations</span><span>Fare history · Expected range</span></div><svg viewBox={`0 0 ${w} ${h}`}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#3578E5" stopOpacity=".3"/><stop offset="1" stopColor="#3578E5" stopOpacity="0"/></linearGradient></defs>{[0,1,2,3].map(i=><line key={i} x1={pad} x2={w-pad} y1={pad+i*45} y2={pad+i*45} className="gridline"/>)}<motion.path d={`${path} L ${w-pad} ${h-pad} L ${pad} ${h-pad} Z`} fill="url(#area)" initial={{opacity:0}} animate={{opacity:1}}/><motion.path key={`e${d.id}`} d={exp} className="expected-line" initial={{pathLength:0}} animate={{pathLength:1}}/><motion.path key={d.id} d={path} className="actual-line" initial={{pathLength:0}} animate={{pathLength:1}}/><circle cx={last[0]} cy={last[1]} r="5" className="current-point"/></svg><p><span>7 days ago</span><span>Today</span></p></div>}
function Explorer(){const[from,setFrom]=useState('DEL'),[to,setTo]=useState('BOM'),[win,setWin]=useState('T+7'),[period,setPeriod]=useState('Weekly'),[flight,setFlight]=useState(0),d=useMemo(()=>routes.find(r=>r.from===from&&r.to===to)||routes[(airports.indexOf(from)*2+airports.indexOf(to))%routes.length],[from,to]);const update=(set:(x:string)=>void,x:string)=>{set(x);setFlight(v=>v+1)},swap=()=>{setFrom(to);setTo(from);setFlight(v=>v+1)};return <section id="explorer" className="section explorer"><div className="ambient-network"/><div className="wrap"><Intro eyebrow="Interactive explorer" title="Track India's Airfare Pulse">Explore live fares, price trends, booking horizons, and market signals across representative Indian routes.</Intro><Reveal><div className="console"><div className="controls"><p className="technical">ROUTE CONFIGURATION</p><div className="route-selects"><label><span>FROM</span><select value={from} onChange={e=>update(setFrom,e.target.value)}>{airports.map(a=><option value={a} key={a}>{airportNames[a]} ({a})</option>)}</select></label><button className="swap" onClick={swap}><Repeat2/></button><motion.i key={flight} className="flight" initial={{x:-12,opacity:0}} animate={{x:14,opacity:1}}><Plane/></motion.i><label><span>TO</span><select value={to} onChange={e=>update(setTo,e.target.value)}>{airports.filter(a=>a!==from).map(a=><option value={a} key={a}>{airportNames[a]} ({a})</option>)}</select></label></div><div className="control"><span>BOOKING WINDOW</span><Segments items={windows} active={win} set={setWin} id="win"/><motion.p key={win} initial={{opacity:0}} animate={{opacity:1}}>{windowCopy[win]}</motion.p></div><div className="control"><span>PERIOD</span><Segments items={['Daily','Weekly','Monthly']} active={period} set={setPeriod} id="period"/></div><div className="refresh"><i/>Market data refreshed 2 min ago</div></div><motion.div key={`${d.id}${win}${period}`} className="intel" initial={{opacity:.7}} animate={{opacity:1}}><div className="headline-metrics"><div><span>MEDIAN FARE</span><strong><Count value={d.fare+windows.indexOf(win)*52} fare/></strong><p><Change value={d.change} light/> vs last week</p></div><div><span>APIx</span><strong>{d.apix}</strong><Change value={d.apixChange} light/></div></div><div className="mini-metrics"><div><span>Volatility</span><strong>{d.volatility}</strong><b className="bars"><i/><i/><i/></b></div><div><span>Confidence</span><strong>{d.confidence}%</strong><b className="confidence"><i style={{width:`${d.confidence}%`}}/></b></div><div><span>Expected Range</span><strong>{d.range}</strong><Spark points={d.expected} dark/></div></div><FareChart d={d}/></motion.div></div></Reveal></div></section>}

const stages=[[Database,'Data Collection','Airlines and OTAs are tracked across major Indian city pairs.'],[ShieldCheck,'Normalization','Fare quotes are cleaned and standardized for true comparability.'],[BarChart3,'Index Computation','Daily, weekly, and monthly signals are aggregated into APIx.'],[Sparkles,'Insight Layer','Trends, anomalies, volatility, and booking-window movement surface.']]
function Methodology(){return <section id="methodology" className="section methodology"><div className="wrap"><Intro eyebrow="Methodology" title="How the Index Works">A disciplined intelligence layer turns fragmented airfare observations into one comparable market signal.</Intro><div className="pipeline"><motion.div className="pipeline-line" initial={{scaleX:0}} whileInView={{scaleX:1}} viewport={{once:true}} transition={{duration:1.2}}/>{stages.map(([Icon,title,text],i)=><Reveal key={title as string} delay={i*.1}><article><div><span><Icon/><i/></span><b>0{i+1}</b></div><h3>{title as string}</h3><p>{text as string}</p></article></Reveal>)}</div></div></section>}
const signals=[[Activity,'Fare anomaly detected','DEL → BLR','31% above expected range','₹9,240','Confidence 92%','anomaly'],[TrendingUp,'Highest weekly increase','DEL → BOM','Up 6.8% this week','₹5,842','Momentum rising','positive'],[Gauge,'Most stable route','BOM → BLR','Variance below 3%','₹4,910','Stable signal','stable'],[RefreshCw,'Strongest booking-window shift','MAA → DEL','Demand moved forward','T+15','Observed today','warning']]
function Signals(){return <section id="signals" className="section signals"><div className="signal-dots"/><div className="wrap"><Intro eyebrow="Signal layer" title="Airfare Market Signals" light>The movements that matter, surfaced from thousands of market observations.</Intro><div className="signal-cards">{signals.map(([Icon,title,route,detail,value,meta,tone],i)=><Reveal key={title as string} delay={i*.07}><article className={tone as string}><div><span><Icon/></span><small>{meta as string}</small></div><p>{title as string}</p><section><div><h3>{route as string}</h3><span>{detail as string}</span></div><strong>{value as string}</strong></section><Spark points={routes[i].points} dark/></article></Reveal>)}</div><Reveal><div className="activity-bar"><div className="activity-wave">{[1,2,3,4,5,6,7,8].map(i=><i key={i}/>)}</div><p><i/>LIVE SIGNAL ACTIVITY</p><div><b>12 <small>Observations</small></b><b>7 <small>Stable Corridors</small></b><b>2 <small>Momentum Shifts</small></b><b>3 <small>Anomalies</small></b></div></div></Reveal></div></section>}

function Network(){const[a,setA]=useState(0),d=routes[a],nodes=[{c:'DEL',x:51,y:14},{c:'BOM',x:28,y:52},{c:'BLR',x:50,y:80},{c:'HYD',x:56,y:60},{c:'MAA',x:64,y:84},{c:'CCU',x:80,y:38}],links=[[0,1],[0,2],[1,2],[2,3],[4,0],[0,5]];return <section className="section network"><div className="wrap"><Intro eyebrow="Network view" title="India Route Intelligence">An artistic pulse of the corridors shaping India's airfare market.</Intro><Reveal><div className="network-shell"><div className="map"><div className="scan"/><span className="technical">COORD / IN-AIRSPACE · OBS / LIVE</span><svg viewBox="0 0 100 100">{links.map(([x,y],i)=><g key={i} className={a===i?'link active':'link'} onClick={()=>setA(i)}><line x1={nodes[x].x} y1={nodes[x].y} x2={nodes[y].x} y2={nodes[y].y}/>{a===i&&<circle r=".9" className="particle"><animateMotion dur="3.8s" repeatCount="indefinite" path={`M${nodes[x].x},${nodes[x].y} L${nodes[y].x},${nodes[y].y}`}/></circle>}</g>)}{nodes.map((n,i)=><g key={n.c} className={links[a].includes(i)?'node selected':'node'}><circle className="ring" cx={n.x} cy={n.y} r="4"/><circle cx={n.x} cy={n.y} r="1.6"/><text x={n.x+3} y={n.y+1}>{n.c}</text></g>)}</svg><em>Select an airport or corridor</em></div><AnimatePresence mode="wait"><motion.aside key={d.id} initial={{opacity:0,x:10}} animate={{opacity:1,x:0}} exit={{opacity:0}}><p className="technical">SELECTED CORRIDOR</p><h3>{d.from} <span>→</span> {d.to}</h3><strong><Count value={d.fare} fare/></strong><p><Change value={d.change}/> this week</p><Spark points={d.points}/><dl><div><dt>APIx</dt><dd>{d.apix}</dd></div><div><dt>Volatility</dt><dd>{d.volatility}</dd></div><div><dt>Expected Range</dt><dd>{d.range}</dd></div><div><dt>Last Refresh</dt><dd>2 min ago</dd></div></dl></motion.aside></AnimatePresence></div></Reveal></div></section>}
const chips=[[Plane,'Airlines','Scheduled airline observations'],[Search,'OTAs','Representative market quotes'],[Route,'Route Basket','Major Indian corridors'],[Gauge,'Booking Windows','T+1 through T+45'],[RefreshCw,'Daily Refresh','Continuously refreshed signals'],[CheckCircle2,'Quality Validation','Cross-source consistency and anomaly checks']]
function Status(){return <div className="status"><div className="radar"><i/><i/><i/></div><p className="technical">SYSTEM STATUS</p><h3><i/>Sources Healthy</h3><div><span><strong>94%</strong>Coverage</span><span><strong>18,420</strong>Observations</span><span><strong>2 min</strong>Last update</span><span><strong>0</strong>Critical failures</span></div></div>}
function Coverage(){return <section id="coverage" className="section coverage"><div className="wrap"><Intro eyebrow="Trust & coverage" title="Built on Broad Market Coverage">A representative, quality-controlled view designed for defensible market insight.</Intro><div className="coverage-layout"><Reveal><div className="counters"><div><strong><Count value={20} suffix="+"/></strong><span>Representative Routes</span></div><div><strong><Count value={5}/></strong><span>Booking Windows</span></div><div><strong><Count value={3}/></strong><span>Index Frequencies</span></div><div><strong>Multi-source</strong><span>Fare Validation</span></div></div><div className="chips">{chips.map(([Icon,l,t])=><div tabIndex={0} key={l as string}><Icon/><span>{l as string}</span><em>{t as string}</em></div>)}</div></Reveal><Reveal delay={.1}><Status/></Reveal></div></div></section>}
function CTA(){return <section className="final"><div className="cta"><div className="cta-grid"/><div className="orbit a"/><div className="orbit b"/><div><p className="eyebrow">The market, made visible</p><h2>Ready to explore India's airfare movement in real time?</h2><section><a href="#explorer" className="button white">Launch Dashboard <ArrowRight/></a><a href="#methodology" className="button outline">View Methodology</a></section></div></div><footer><span><Plane/>AeroIndex India</span><p>Airfare intelligence for a more transparent market.</p><small>© 2026 AeroIndex</small></footer></section>}
export default function App(){return <main><Progress/><Hero/><Explorer/><Methodology/><Signals/><Network/><Coverage/><CTA/></main>}
